"""Thin wrapper around the free-tier Groq LLM API.

Groq hosts open-weight models (e.g. Llama 3.3) and offers a generous free
tier, which satisfies the "no paid APIs" requirement of this project.
"""

from __future__ import annotations

from typing import Iterator, List, Optional

from backend.utils.config import settings
from backend.utils.logger import get_logger

logger = get_logger(__name__)


class GroqLLMError(RuntimeError):
    """Raised when a call to the Groq API fails."""


class GroqLLM:
    """Synchronous and streaming chat-completion client for Groq."""

    def __init__(
        self,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> None:
        self.model = model or settings.groq_model
        self.temperature = (
            temperature if temperature is not None else settings.groq_temperature
        )
        self.max_tokens = max_tokens or settings.groq_max_tokens
        self._client = None

    def _get_client(self):
        if self._client is not None:
            return self._client
        try:
            from groq import Groq
        except ImportError as exc:  # pragma: no cover - defensive
            raise GroqLLMError(
                "The `groq` package is not installed. Run `pip install groq`."
            ) from exc

        if not settings.groq_api_key:
            raise GroqLLMError(
                "GROQ_API_KEY is not set. Please configure it in your .env file."
            )

        self._client = Groq(api_key=settings.groq_api_key)
        return self._client

    @staticmethod
    def _to_groq_messages(
        system_prompt: str, messages: List[dict]
    ) -> List[dict]:
        formatted = [{"role": "system", "content": system_prompt}]
        formatted.extend(messages)
        return formatted

    def generate(self, system_prompt: str, messages: List[dict]) -> str:
        """Generate a complete (non-streaming) chat completion."""

        client = self._get_client()
        try:
            response = client.chat.completions.create(
                model=self.model,
                messages=self._to_groq_messages(system_prompt, messages),
                temperature=self.temperature,
                max_tokens=self.max_tokens,
                stream=False,
            )
        except Exception as exc:  # noqa: BLE001
            logger.exception("Groq generation failed")
            raise GroqLLMError(f"Groq API call failed: {exc}") from exc
        return response.choices[0].message.content or ""

    def stream(self, system_prompt: str, messages: List[dict]) -> Iterator[str]:
        """Yield the response incrementally as it is generated by Groq."""

        client = self._get_client()
        try:
            stream = client.chat.completions.create(
                model=self.model,
                messages=self._to_groq_messages(system_prompt, messages),
                temperature=self.temperature,
                max_tokens=self.max_tokens,
                stream=True,
            )
            for chunk in stream:
                delta = chunk.choices[0].delta
                content = getattr(delta, "content", None)
                if content:
                    yield content
        except Exception as exc:  # noqa: BLE001
            logger.exception("Groq streaming failed")
            raise GroqLLMError(f"Groq streaming call failed: {exc}") from exc


_groq_llm_singleton: GroqLLM | None = None


def get_groq_llm() -> GroqLLM:
    """Return a process-wide singleton :class:`GroqLLM` instance."""

    global _groq_llm_singleton
    if _groq_llm_singleton is None:
        _groq_llm_singleton = GroqLLM()
    return _groq_llm_singleton
